# Generated by Django 3.2.4 on 2021-06-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_author_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
    ]
